### ISSUE TITLE
Type of the current meeting or discussion

### ISSUE THREAD

**Issue by PPTLC** [PartiPirate/congressus#107]
In https://congressus.partipirate.org/construction.php?id=XXXX

see directly the type of meeting (meeting or discussion) in the same way as the convoked group.

**Comment by farlistener** [comment]
Hum the form, construction or meeting, has two shapes, so for me it's irrelevant

**Comment by PPTLC** [comment]
The matter for the user is to know on each page where he is and what he can do. For you as the main developper it may be obvious but for the users it must be too. In my point of view at the moment it's not. The tools must be adapt to the human and to the greatest number, the opposite seems to me less relevant
NB :

**Comment by farlistener** [comment]
Please, check the interfaces
