### ISSUE TITLE
Reminder of the current type of vote

### ISSUE THREAD

**Issue by PPTLC** [PartiPirate/congressus#108]
In https://congressus.partipirate.org/construction.php?id=XXXX

have a reminder of the voting method and the number of votes to be cast in a discussion in the same way as the convoked group.

See https://github.com/PartiPirate/congressus/issues/107

**Comment by farlistener** [comment]
as in #106 the matter is the "voting method", I don't understand this "need" as I dont' see where this information is needed.

in the decision process (meeting and decisions), each motion delivers this information.
in the construction process (discussion and co-construction), each motion has the same behavior : "ok", "doubtful" and "ko"

so, what is a "voting method" ?

**Comment by PPTLC** [comment]
By "voting method" I mean the type of voting system : "election by majority vote" or "election by majority judgment" or what ever you'll implement in Congressus.

**Comment by farlistener** [comment]
Like I said, in the meeting mode, each motion has this information available. In the construction mode, it's not a vote.
