### ISSUE TITLE
Thème sombre : Problème affichage calendrier

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/congressus#129]
Avec le thème sombre, quand on passe la souris sur un jour, l'ensemble de la semaine sur surligne, mais en blanc, ce qui rend le calendrier peu lisible : 

![image](https://user-images.githubusercontent.com/6787800/39752516-fc9a8e3c-52bb-11e8-9544-a61da0a32c97.png)

**Comment by farlistener** [comment]
Et maintenant ?

**Comment by Farocs** [comment]
Parfait
