### ISSUE TITLE
Couleur du texte ne reflétant pas la validation de la décision

### ISSUE THREAD

**Issue by JeeyPP** [PartiPirate/congressus#135]
https://congressus.partipirate.org/decisions.php
Apparemment, le couleur du texte utilisé pour la présentation des pour/contre ne correspond pas pour certains votes : 
exemple : 
![image](https://user-images.githubusercontent.com/38607888/40891653-06287b84-678a-11e8-9c39-9308f76d8a3a.png)
Par contre, pour d'autres, c'est bien ok : 
![image](https://user-images.githubusercontent.com/38607888/40891659-2e2be7ba-678a-11e8-9672-b4b4283a9397.png)

Voilà. Bisous.

**Comment by farlistener** [comment]
Duplicate of #134
