### ISSUE TITLE
Debug message : Division By Zero on main page

### ISSUE THREAD

**Issue by thoth101010** [PartiPirate/congressus#140]
There is a debug message on the [main page](https://congressus.partipirate.org/)
` Warning: Division by zero in /usr/share/nginx/html/index.php on line 43`
![1529877527](https://user-images.githubusercontent.com/16567529/41824085-b021ec48-780a-11e8-887e-230ca40375d2.png)

**Comment by farlistener** [comment]
Solved but not commited
