### ISSUE TITLE
Ajouter un responsable de la tâche dans la liste des tâches en cours.

### ISSUE THREAD

**Issue by Zidjinn** [PartiPirate/congressus#142]
- Pouvoir ajouter un responsable de la tâche dans la liste des tâches en cours. (Pour ne pas avoir à faire appel à la mémoire des secrétaires de séance).

- Permettre l'ajout de plusieurs responsables en cas de responsabilité partagée.

**Comment by farlistener** [comment]
C'est prévu dans la liste de chose à faire ...
