### ISSUE TITLE
Faire apparaître la couleur du vote autour des soutiens 

### ISSUE THREAD

**Issue by AurifexPP** [PartiPirate/congressus#147]
Effet recherché : un cercle de couleur vert, orange ou rouge autour du nom de l'utilisateur pour indiquer quel est la nature de son vote dans la partie co-construction. 

Objectif : Avoir plus de transparence sur le process et permettre d'engager le dialogue avec les personnes qui sont mitigés ou défavorables pour permettre de faire ressortir une proposition à même de trouver une majorité.

**Comment by farlistener** [comment]
Avec un paramètre : 

- $config["parameters"]["show_support"] = true;
