### ISSUE TITLE
Créer une fonction "template" pour les réunions 

### ISSUE THREAD

**Issue by AurifexPP** [PartiPirate/congressus#148]
Effet recherché : Dans le cadre d'une réunion co-construction ou de décision, il serait pratique d'avoir des template pour avoir une structure fixe pour certaines réunions.
Ces templates resteraient éditables quoi qu'il arrive pour permettre une souplesse dans l'organisation.

**Comment by keithgoldstein** [comment]
Each user should have the ability to create and edit templates. An easy way to create a template would be to just create a meeting with the content you wanted to use routinely. It should then be possible to copy that saved meeting to be used as a template for new meetings.

**Comment by farlistener** [comment]
It's normally done as you wish

**Comment by keithgoldstein** [comment]
Thank you so much for providing this copy feature :) I am using each time last weeks template for the meetings.
