### ISSUE TITLE
Plus de visibilité pour les boutons dans l'interface de vote au jugement majoritaire

### ISSUE THREAD

**Issue by thoth101010** [PartiPirate/congressus#152]
Ajouter des effets pour mieux voir quel est l'option sélectionnée
Par exemple avec les jugements "bien" et "très bien", même avec le contour colorié, c'est difficile de voir la différence 

![1537911304](https://user-images.githubusercontent.com/16567529/46044720-4119e680-c124-11e8-9894-94bc153c3d12.png)

![1537911327](https://user-images.githubusercontent.com/16567529/46044721-4119e680-c124-11e8-88a4-a50a5bfed9c4.png)

Edit : rendre les autres couleurs plus grisées par exemple

**Comment by farlistener** [comment]
À tester
