### ISSUE TITLE
Export Markdown/Wiki, passage à la ligne après chaque titre

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/congressus#19]
Bonjour,

Après quelques tests, je remarque que l'export Markdown ne passe pas à la ligne à chaque élément important (titre ou élément type modèle).

Exemple d'export :

=Réunion du Bureau National= ==Convoqués== * Bureau National : *** 0/0 ==test== ceci est un test de titre

Devrait être :
=Réunion du Bureau National=
==Convoqués==
* Bureau National : *** 0/0
==test==
ceci est un test de titre

**Comment by farlistener** [comment]
Le code source de la page contient bien les sauts de ligne
