### ISSUE TITLE
Affichage mode Kanban

### ISSUE THREAD

**Issue by FlorieLVM** [PartiPirate/congressus#192]
La page d'accueil doit être compréhensible et lisible. Elle peut être divisée en trois colonnes dans le style du kanban.
Colonne 1 : Les réunions à venir.
Colonne 2 : Les réunions en cours.
Colonne 3 : Les réunions terminées

On pourrait envisager que ces réunions soient indiquées dans des boutons de la couleur correspondant aux type de réunions du PP avec le nom de la réunion en taille normale, et en plus petit les dates de début et de fin.

**Comment by farlistener** [comment]
Gros commit à discuter
