### ISSUE TITLE
Affichage des réunions différencié selon le groupe personae dont on est membre

### ISSUE THREAD

**Issue by FlorieLVM** [PartiPirate/congressus#193]
Sur la page de décision, il faudrait un affichage des réunions qui permette d'accéder en premier lieu aux réunions et décisions des groupes dont on fait partie dans personae.

Ainsi, le Pirate qui n'est pas membre de l'Association de Financement du PP ne verra pas le CR de la dernière AG s'afficher en premier.

Il faudrait également un affichage dynamique permettant d'afficher le CR des réunions quand on glisse la souris dessus ou quand on clique dessus.

**Comment by farlistener** [comment]
À discuter pour savoir si le résultat est pour l'instant satisfaisant
