### ISSUE TITLE
Annuler une clôture de séance

### ISSUE THREAD

**Issue by der-siebte-schatten** [PartiPirate/congressus#242]
En cas de boulette (si jamais double-clic sur "Ouvrir la séance", clic au mauvais endroit ou oubli de ceux qui n'ont pas encore voté), il serait bon de laisser la possibilité au président de la séance la possibilité de rouvrir la séance pendant une petite période de temps (disons 30 minutes). Cela ne serait pas pris en compte dans le CR de séance.

Dans ce cas aussi, il faudrait interdire la génération de CR de séance pendant cette période de temps, pour éviter les faux CR.

**Comment by farlistener** [comment]
> Dans ce cas aussi, il faudrait interdire la génération de CR de séance pendant cette période de temps, pour éviter les faux CR.

Alors je veux bien, mais aujourd'hui on clôt la séance et ensuite on publie le CR ... plus préférer des mécanisme automatique de correction si on rouvre et referme une séance
