### ISSUE TITLE
« Amendement » -> « Motion »

### ISSUE THREAD

**Issue by Bayesianass** [PartiPirate/congressus#245]
Une fois connecté en tant que membre, et lors de l'accès à une session de dépôt de l'assemblée permanente sur congressus, un bouton indique, pour chaque catégorie « Ajouter un amendement ». Or, nous avons pris pour habitude de parler de « motions » pour le texte initial, et  « d'amendements » lorsqu'il s'agit de modifications du texte. Il serait intéressant d'harmoniser les termes et de conserver cette distinction tant dans nos échanges, dans les statuts que dans nos outils. Il faudrait donc modifier « Ajouter un amendement » pour que celui devienne « Ajouter une motion ».

De même, les catégories vides renvoient « Auncun amendement proposé » et devraient indiquer « Aucune motion proposée ».

**Comment by farlistener** [comment]
De même pour le titre de la popin modale
