### ISSUE TITLE
Recherche de Réunion Par équipages

### ISSUE THREAD

**Issue by Bapeuh** [PartiPirate/congressus#262]
L'onglet "Réunion" 
Modifier le bouton "Réunion d'instance" en "Réunion Equipage" (ou garder le même nom)
Garder le même affichage. Avec la listes des différents équipages.
En cliquant sur l'équipage voulu, en dessous la liste des réunion de l'équipage s'affiche, de la plus récente à la plus ancienne.

**Comment by farlistener** [comment]
La page reste en réunion d'instance, toutefois elle a été repensée pour afficher les réunions par "équipage"
Le statut des réunions (en attente, en cours, finie) est aussi coloré pour visualiser facilement les différentes réunions

**Comment by farlistener** [comment]
RAF : 

- Visualiser par groupe plutôt que par thème
- Voir possiblement les archives
- Externaliser la notion de groupe par défaut
