### ISSUE TITLE
Lors de l'édition de champ de texte, le texte initiale ne s'éfface pas

### ISSUE THREAD

**Issue by florentls** [PartiPirate/congressus#37]
Par exemple lors de la création de l'ordre du jour, lorsqu'on cré un nouveau sujet, le texte "Nouveau point" reste écrit et ne s’efface pas.

j'ai l'impression que c'est le cas pour toutes les autres zones de texte éditables.

**Comment by florentls** [comment]
J'ai vu cela sous Debian Testing/Firefox 45.3

**Comment by farlistener** [comment]
Il va falloir motiver pour un autre comportement.

S'il n'y a plus de label, il est difficile à la zone
