### ISSUE TITLE
Autolike

### ISSUE THREAD

**Issue by Zidjinn** [PartiPirate/congressus#38]
On peux s'auto +1 ou -1, s'est bof. Supprimer cette possibilitée p-être ?

**Comment by farlistener** [comment]
C'est pas faux

**Comment by Relf-PP** [comment]
ah, moi j'aimais bien.

**Comment by farlistener** [comment]
J'ai tranché, ça sera non. 
Quand on retranscrit les paroles de quelqu'un, on peut aimer ce qu'il dit. Or on peut l'avoir fait avec "notre" parole
