### ISSUE TITLE
Point précédent / dernier point d'une réunion

### ISSUE THREAD

**Issue by Zidjinn** [PartiPirate/congressus#40]
Dans le (cadre) d'un point de réunion (en cours) il y a deux boutons : Le bouton "point précédent" et le bouton "point suivant" qui permettent de circuler entre les points de l'odj sans cliquer à droite sur le sommaire.

Par contre quand on est sur le dernier point et qu'on clique sur le bouton "point suivant", on retourne à l'avant dernier. Ce qui est une erreur. Il faudrait soit faire en sorte que le bouton n'entraine aucune action, soit qu'il permette de retourner au point 1.

exemple : https://congressus.partipirate.org/meeting.php?id=53
(au point 12, le bouton page suivante nous fait retourner au point 11)

**Comment by farlistener** [comment]
> (au point 12, le bouton page suivante nous fait retourner au point 11)

En fait le bouton page précédente prenait la place du bouton suivant.
Les boutons restent maintenant toujours.
