### ISSUE TITLE
Possibilité de définir un chemin mumble pour une réunion

### ISSUE THREAD

**Issue by farlistener** [PartiPirate/congressus#43]
_c.f._ https://wiki.mumble.info/wiki/Mumble_URL

Il est possible de donner une url pour arriver sur un serveur mumble avec l'application mumble directement sur le bon serveur, avec le bon pseudo, sur le bon canal.

De fait il faudrait pouvoir choisir un tel chemin pour une réunion donnée, et donc afficher un lien de connexion vers le bon canal mumble.

**Comment by farlistener** [comment]
RAF (Reste à faire) : 

- Une erreur quand le canal mumble n'est pas (ou n'a pas été) choisi
- Des erreurs d'alignements dans la page meeting

Pour le reste :+1:

**Comment by treyssatvincent** [comment]
Pour les erreurs d'alignements quel est le résultat attendu ?

**Comment by farlistener** [comment]
Que les icônes et textes soient alignés avec les lignes précédents, pas plus

**Comment by farlistener** [comment]
Nickel :+1:
