### ISSUE TITLE
Ajout des meta twitter/facebook/g+

### ISSUE THREAD

**Issue by farlistener** [PartiPirate/congressus#52]
Comme ceci : 

    
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://adhesion.partipirate.org/" />
    <meta property="og:title" content="Parti Pirate - Don/Adhésion" />
    <meta property="og:description" content="Devenez adhérent-e du Parti Pirate ou donnez pour son fonctionnement." />
    <meta property="og:image" content="https://adhesion.partipirate.org/assets/img/logo_pp_circle.png" />
    
    <meta itemprop="name" content="Parti Pirate - Don/Adhésion" />
    <meta itemprop="description" content="Devenez adhérent-e du Parti Pirate ou donnez pour son fonctionnement." />
    <meta itemprop="image" content="https://adhesion.partipirate.org/assets/img/logo_pp_circle.png" />
    
    <meta name="twitter:site" content="@partipirate" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:url" content="https://adhesion.partipirate.org/" />
    <meta name="twitter:title" content="Parti Pirate - Don/Adhésion" />
    <meta name="twitter:description" content="Devenez adhérent-e du Parti Pirate ou donnez pour son fonctionnement." />
    <meta name="twitter:image" content="https://adhesion.partipirate.org/assets/img/logo_pp_circle.png" />

**Comment by treyssatvincent** [comment]
Proposition : du contenu générique sur toutes les pages sauf sur meeting.php où : 
- title : Nom de la réunion
- description : Premier ordre du jour

Pour le reste : 
title : "Parti Pirate - Congressus"
description : "Congressus permet de gérer des réunions en fonction de différents groupes et de définir qui est convoqué aux réunions, qui a le droit de vote, définir des motions."

**Comment by farlistener** [comment]
Ça me va

**Comment by farlistener** [comment]
J'ai du faire un revert tu as forcé ton commit sur des pages qui n'étaient pas à jour

**Comment by treyssatvincent** [comment]
Ah oui j'ai oublié de sortir de mon checkout. Je recommence.

**Comment by farlistener** [comment]
Fonctionne nickel :+1:
