### ISSUE TITLE
Vote Méthode Jugement Majoritaire

### ISSUE THREAD

**Issue by farlistener** [PartiPirate/congressus#55]

**Comment by farlistener** [comment]
Le vote "autonome" fonctionne avec le jugement majoritaire

RAF : 

Affiche du vote en jugement majoritaire pour le vote en réunion
Calcul du résultat du vote majoritaire

**Comment by Relf-PP** [comment]
Ya ceux pour qui RAF veut dire Rien à Foutre et ya ceux pour qui ça veut dire Reste A Faire.  😛

**Comment by farlistener** [comment]
RAF : 

- Affichage du résultat du vote JM en tableau
- Mise à jour des exports

**Comment by farlistener** [comment]
externalisation de "Affichage du résultat du vote JM en tableau" cf #58
