### ISSUE TITLE
Probleme des exports de CR - Le PDF

### ISSUE THREAD

**Issue by Relf-PP** [PartiPirate/congressus#72]
Sur la reunion Stratcom du 06/07 (https://congressus.partipirate.org/meeting.php?id=185), l'export pdf crée bien un pdf,mais le contenu n'est pas bon. Il manque énormément d'infos.
Le contenu s’arrête à un lien. Corrélation n'est pas causation, mais ça mérite analyse. 
Problème détecté sous ubuntu 16.04 et Windows 7.

**Comment by farlistener** [comment]
Celui-là je prends, j'ai vu ça hier, il faut que j'investigue

**Comment by farlistener** [comment]
Le problème est principalement dû à un lien dans l'une des descriptions
