### ISSUE TITLE
Probleme des exports de CR - Le wiki 

### ISSUE THREAD

**Issue by Relf-PP** [PartiPirate/congressus#73]
Il n'y a aucun retour à la ligne après la fin de la description du premier point de l'ordre du jour, même pour un changement de sujet de l'ordre du jour.
J'ai verifié en copiant-collant dans une page wiki et je confirme que les retours à la ligne ne sont pas pris en compte.
Cf https://congressus.partipirate.org/meeting.php?id=185 toujours

**Comment by treyssatvincent** [comment]
Résolu non ?

**Comment by Relf-PP** [comment]
Ca y ressemble,oui.
