### ISSUE TITLE
Rajouter un lien "Mot de passe perdu"

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/congressus#81]
Rajouter un lien "mot de passe perdu" qui redirige vers la page lostpasswd de Galette

**Comment by treyssatvincent** [comment]
Ça ne serait pas plus logique de rajouter un lien vers cette page : https://congressus.partipirate.org/forgotten.php ?

**Comment by treyssatvincent** [comment]
Après avoir essayé, il vaux mieux utiliser celui de Galette en effet.

**Comment by Farocs** [comment]
Je me suis basé sur l'approche de l'installation actuelle (avec un congressus dépendant de Galette). Maintenant, si Congressus a la possibilité d'être indépendant, il faudra au choix rediriger vers sa propre page "mot de passe perdu" si pas de liaison et vers Galette autrement je pense :)

**Comment by farlistener** [comment]
> Maintenant, si Congressus a la possibilité d'être indépendant, il faudra au choix rediriger vers sa propre page "mot de passe perdu" si pas de liaison et vers Galette autrement je pense :)

Tout à fait
