### ISSUE TITLE
Ajouter lien mumble dans convocation

### ISSUE THREAD

**Issue by farlistener** [PartiPirate/congressus#84]
Dans le cadre d'une réunion prévue sur mumble, le champ adresse est vide.

Il faudrait rajouter le lien mumble

**Comment by treyssatvincent** [comment]
Le champs "Adresse du lieu" ?

**Comment by farlistener** [comment]
Si ça correspond à ça dans le mail "L'espace de rencontre sur mumble se fera à cette adresse :"
Je dirai oui
